---
title: "paper_reproducibility"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{paper_reproducibility}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(InterCellar)
library(ggplot2)
library(tidyr)
library(scales)
```

## Result 1. Reduced Tcells interactions and increased macrophages in severe patients compared to moderate

```{r comp_barplot, eval=FALSE}
# Read csv files saved from InterCellar
mod_barplot_df_all <- read.csv("../../paper_reproducibility/mod_barplots/Cluster-verse_barplot.csv")
sev_barplot_df_all <- read.csv("../../paper_reproducibility/sev_barplots/Cluster-verse_barplot.csv")

difference_df <- data.frame(clusters = unique(c(mod_barplot_df_all$clusters,
                                              sev_barplot_df_all$clusters)))
difference_df$tot_sev <- sev_barplot_df_all$n_paracrine + sev_barplot_df_all$n_autocrine
difference_df$tot_mod <- mod_barplot_df_all$n_paracrine + mod_barplot_df_all$n_autocrine
difference_df$diff_sev_mod <- difference_df$tot_sev - difference_df$tot_mod

# From wide to long
mod_barplot_df_all <- tidyr::pivot_longer(mod_barplot_df_all, 
                                         cols = c("n_paracrine","n_autocrine"), 
                                         names_to = "type", 
                                         names_prefix = "n_",
                                         values_to = "n_int")
sev_barplot_df_all <- tidyr::pivot_longer(sev_barplot_df_all, 
                                         cols = c("n_paracrine","n_autocrine"), 
                                         names_to = "type", 
                                         names_prefix = "n_",
                                         values_to = "n_int")

# Add column for phenotype
mod_barplot_df_all$pheno <- "moderate"
sev_barplot_df_all$pheno <- "critical"
  
# Bind dfs

barplot_df <- rbind(sev_barplot_df_all, mod_barplot_df_all)

cluster.colors <- scales::hue_pal(c = 80, l = 80)(length(unique(barplot_df$clusters)))
  
g <- ggplot() +
        geom_bar(data = subset(barplot_df, pheno == "critical"), 
                 aes(y = n_int, x = clusters, 
                            fill = type, 
                            color = clusters),
                 position="stack", stat="identity") +
        geom_bar(data = subset(barplot_df, pheno == "moderate"), 
                 aes(y = -n_int, x = clusters, 
                            fill = type, 
                            color = clusters),
                 position="stack", stat="identity") +
        geom_point(data = difference_df, aes(x = clusters, y = diff_sev_mod)) +
        geom_line(data = difference_df, aes(x = clusters, y = diff_sev_mod, group = 1), 
                  stat = "identity") +
        theme_minimal() +
        scale_fill_manual(values = c("#606060", "#C0C0C0")) + 
        scale_color_manual(values = cluster.colors) +
        theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1), 
              text = element_text(size=20),
              strip.text = element_blank()) +
        guides(color = FALSE) + 
        labs(x = "Clusters", y = "# Interactions", 
             title = "Total number of interactions per cluster") 
 
png("../../paper_reproducibility/Barplot_comp_severeVSmoderate.png", width = 800)
plot(g)
dev.off()
pdf("../../paper_reproducibility/Barplot_comp_severeVSmoderate.pdf")
plot(g)
dev.off()


## Comparison by Clusters
library(fmsb)
library(data.table)
library(tibble)


get_radar_df <- function(mod_df, sev_df){
  df <- cbind(mod_df, sev_df$Num_int)
  
  cluster_names <- df$Clusters
  # add max and min
  max_nint <- max(df[, -1])
  df <- add_column(df, max_nint, .after = "Clusters")
  df <- add_column(df, "min_nint" = 0, .after = "max_nint")
  
  radar_df <- transpose(df[, -1])
  
  rownames(radar_df) <- c("max", "min", "moderate", "critical")
  colnames(radar_df) <- cluster_names
  return(radar_df)
}


create_radarchart <- function(data, color = c("#438ECC", "#E97778"), 
                                        vlabels = colnames(data), vlcex = 1.2,
                                        title = NULL, ...){
  radarchart(
    data, axistype = 1,
    # Customize the polygon
    pcol = color, pfcol = scales::alpha(color, 0.5), plwd = 2, plty = 1,
    # Customize the grid
    cglcol = "grey", cglty = 1, cglwd = 0.8,
    # Customize the axis
    axislabcol = "grey30", 
    # Variable labels
    vlcex = vlcex, vlabels = vlabels,
    caxislabels = round(seq(from = 0, to = data["max",1], length.out = 5)), 
    title = title, ...
  )
  legend(
  x = "bottomleft", legend = rownames(data[-c(1,2),]), horiz = FALSE,
  bty = "n", pch = 20 , col = color,
  text.col = "black", cex = 1, pt.cex = 1.5
  )
}


# MoMa
# Read csv files saved from InterCellar
mod_moma <- read.csv("../../paper_reproducibility/mod_barplots/Cluster-verse_barplot_clustMoMa.csv")
sev_moma <- read.csv("../../paper_reproducibility/sev_barplots/Cluster-verse_barplot_clustMoMa.csv")
png("../../paper_reproducibility/Radar_MoMa.png", width = 500)
create_radarchart(data = get_radar_df(mod_moma, sev_moma))
dev.off()

pdf("../../paper_reproducibility/Radar_MoMa.pdf")
create_radarchart(data = get_radar_df(mod_moma, sev_moma))
dev.off()

# nrMa
# Read csv files saved from InterCellar
mod_nrma <- read.csv("../../paper_reproducibility/mod_barplots/Cluster-verse_barplot_clustnrMa.csv")
sev_nrma <- read.csv("../../paper_reproducibility/sev_barplots/Cluster-verse_barplot_clustnrMa.csv")
png("../../paper_reproducibility/Radar_nrMa.png", width = 500)
create_radarchart(data = get_radar_df(mod_nrma, sev_nrma))
dev.off()
pdf("../../paper_reproducibility/Radar_nrMa.pdf")
create_radarchart(data = get_radar_df(mod_nrma, sev_nrma))
dev.off()

# CTL
# Read csv files saved from InterCellar
mod_ctl <- read.csv("../../paper_reproducibility/mod_barplots/Cluster-verse_barplot_clustCTL.csv")
sev_ctl <- read.csv("../../paper_reproducibility/sev_barplots/Cluster-verse_barplot_clustCTL.csv")
png("../../paper_reproducibility/Radar_CTL.png", width = 500)
create_radarchart(data = get_radar_df(mod_ctl, sev_ctl))
dev.off()
pdf("../../paper_reproducibility/Radar_CTL.pdf")
create_radarchart(data = get_radar_df(mod_ctl, sev_ctl))
dev.off()

# Treg
# Read csv files saved from InterCellar
mod_treg <- read.csv("../../paper_reproducibility/mod_barplots/Cluster-verse_barplot_clustTreg.csv")
sev_treg <- read.csv("../../paper_reproducibility/sev_barplots/Cluster-verse_barplot_clustTreg.csv")
png("../../paper_reproducibility/Radar_Treg.png", width = 500)
create_radarchart(data = get_radar_df(mod_treg, sev_treg))
dev.off()
pdf("../../paper_reproducibility/Radar_Treg.pdf")
create_radarchart(data = get_radar_df(mod_treg, sev_treg))
dev.off()


##---- Epithelial
# Secretory
# Read csv files saved from InterCellar
mod_df <- read.csv("../../paper_reproducibility/mod_barplots/Cluster-verse_barplot_clustSecretory.csv")
sev_df <- read.csv("../../paper_reproducibility/sev_barplots/Cluster-verse_barplot_clustSecretory.csv")
png("../../paper_reproducibility/Radar_Secretory.png", width = 500)
create_radarchart(data = get_radar_df(mod_df, sev_df))
dev.off()
pdf("../../paper_reproducibility/Radar_Secretory.pdf")
create_radarchart(data = get_radar_df(mod_df, sev_df))
dev.off()

# Secretory-diff
# Read csv files saved from InterCellar
mod_df <- read.csv("../../paper_reproducibility/mod_barplots/Cluster-verse_barplot_clustSecretory-diff.csv")
sev_df <- read.csv("../../paper_reproducibility/sev_barplots/Cluster-verse_barplot_clustSecretory-diff.csv")
png("../../paper_reproducibility/Radar_Secretory_diff.png", width = 500)
create_radarchart(data = get_radar_df(mod_df, sev_df))
dev.off()
pdf("../../paper_reproducibility/Radar_Secretory_diff.pdf")
create_radarchart(data = get_radar_df(mod_df, sev_df))
dev.off()

# Ciliated
# Read csv files saved from InterCellar
mod_df <- read.csv("../../paper_reproducibility/mod_barplots/Cluster-verse_barplot_clustCiliated.csv")
sev_df <- read.csv("../../paper_reproducibility/sev_barplots/Cluster-verse_barplot_clustCiliated.csv")
png("../../paper_reproducibility/Radar_Ciliated.png", width = 500)
create_radarchart(data = get_radar_df(mod_df, sev_df))
dev.off()
pdf("../../paper_reproducibility/Radar_Ciliated.pdf")
create_radarchart(data = get_radar_df(mod_df, sev_df))
dev.off()

# Ciliated-diff
# Read csv files saved from InterCellar
mod_df <- read.csv("../../paper_reproducibility/mod_barplots/Cluster-verse_barplot_clustCiliated-diff.csv")
sev_df <- read.csv("../../paper_reproducibility/sev_barplots/Cluster-verse_barplot_clustCiliated-diff.csv")
png("../../paper_reproducibility/Radar_Ciliated_diff.png", width = 500)
create_radarchart(data = get_radar_df(mod_df, sev_df))
dev.off()
pdf("../../paper_reproducibility/Radar_Ciliated_diff.pdf")
create_radarchart(data = get_radar_df(mod_df, sev_df))
dev.off()

```
