#' Input Data example
#'
#' A dataset obtained from Tirosh et al melanoma dataset, running CellPhoneDBv2.
#' This data is generated by InterCellar running read.CPDBv2()
#'
#' @format A data frame with 5638 rows and 11 variables:
#' \describe{
#'   \item{int_pair}{interaction pair name, geneA & geneB}
#'   \item{geneA}{name, hgnc_symbol}
#'   \item{geneB}{name, hgnc_symbol}
#'   \item{typeA}{molecular type of geneA, either L (ligand) or R (receptor)}
#'   \item{typeB}{molecular type of geneB, either L (ligand) or R (receptor)}
#'   \item{clustA}{name of first cluster, either character or number}
#'   \item{clustB}{name of second cluster, either character or number}
#'   \item{score}{int-pair score as avg expression of geneA and geneB over 
#'   clustA and clustB, decimal}
#'   \item{p_value}{int-pair pvalue, decimal}
#'   \item{annotation_strategy}{database from which the int-pair was retrieved}
#'   \item{int.type}{either autocrine or paracrine}
#' }
"input.data"