#' upload UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd 
#'
#' @importFrom shiny NS tagList fluidRow column selectInput conditionalPanel 
#' textOutput tabPanel
#' @importFrom shinyFiles shinyDirButton shinyDirChoose getVolumes parseDirPath
#' @importFrom shinydashboard tabBox 
#' @importFrom fs path_home


mod_upload_ui <- function(id){
  ns <- NS(id)
  text.cpdb <- "Please select the output folder generated by CPDB (v2). When the
  statistical analysis was run, this folder contains 4 .txt files 
  (<em>deconvoluted</em>, <em>means</em>, <em>pvalues</em> and 
  <em>significant_means</em>). In this case, InterCellar will use results stored
  in <em>significant_means</em> for further analyses. If no statistical analysis
  was run, InterCellar will rely on <em>means</em>."
  text.scsignalR <- "Please select the output folder generated by 
  SingleCellSignalR. This is by default named <em>cell-signaling</em> and 
  contains a collection of .txt files, one for each clusters pair considered."
  text.cellchat <- "InterCellar expects a dataframe consisting of inferred cell-cell 
  communications at the level of ligand-receptor interactions. This can be obtained
  by running CellChat's function <em>subsetCommunication (with param slot.name = 'net')</em>. 
  We recommend saving this dataframe as a .csv file (quote = FALSE), but .tsv and .xlsx files are also supported."
  
  tagList(
    fluidRow(
      column(width = 6,
             h2("Upload cell-cell interactions")),
      
      
    ),
    
      tabBox(
        width = NULL,
        
        
        tabPanel(h4("From supported tools"),
                 fluidRow(
                   column(4,
                          selectInput(ns("select_input_tool"),
                                      label = h4("Select tool:"),
                                      choices = list("CellPhoneDB v2" = "cpdbv2",
                                                     "SingleCellSignalR" = "scsignalR",
                                                     "CellChat" = "cellchat"),
                                      multiple = FALSE)
                   ),
                   column(8,
                          conditionalPanel(
                            condition = "input.select_input_tool == 'cpdbv2'",
                            ns = ns,
                            p(div(HTML(text.cpdb)))
                            
                            
                          ),
                          conditionalPanel(
                            condition = "input.select_input_tool == 'scsignalR'",
                            ns = ns,
                            p(div(HTML(text.scsignalR)))
                            
                            
                          ),
                          conditionalPanel(
                            condition = "input.select_input_tool == 'cellchat'",
                            ns = ns,
                            p(div(HTML(text.cellchat)))
                            
                            
                          ),
                          conditionalPanel(
                            condition = "input.select_input_tool == 'cpdbv2' | input.select_input_tool == 'scsignalR'",
                            ns = ns,
                            shinyFiles::shinyDirButton(ns("directory"), 
                                                       "Select folder", 
                                                       "Please select a folder")
                          ),
                          conditionalPanel(
                            condition = "input.select_input_tool == 'cellchat'",
                            ns = ns,
                            fileInput(ns("input_file"), 
                                      "Choose Input File (.csv/.tsv/.xlsx)", 
                                      multiple = FALSE, 
                                      accept = c(".csv", ".tsv", ".xlsx")),
                            actionButton(ns("input_file_button"), 
                                                  label = tags$b("Go!"))

                          ),
                          
                   ))),
        tabPanel(h4("From custom analysis"),
                 mod_upload_custom_ui("upload_custom_ui_1")
        )
      )#tabbox
      
             
             
      
  )
  
  
}
    
#' upload Server Function
#'
#' @importFrom shinyalert shinyalert
#' @noRd 
mod_upload_server <- function(id) {
  moduleServer(id, function(input, output, session) {
    
    rv <- reactiveValues(data = NULL)
    
    
    ### For supported tools requiring folders
    volumes <- c(Home = fs::path_home(),  getVolumes()())
    shinyDirChoose(input, "directory", roots = volumes, session = session, 
                   restrictions = system.file(package = "base"))
    
    input_folder <- reactive({
      req(input$directory)
      parseDirPath(volumes, input$directory)
    })
    
    
    ### Read input and construct datatable
    observeEvent(input$directory, {
      req(input_folder())
      if(input$select_input_tool == 'cpdbv2'){
        files <- list.files(input_folder())
        if("means.txt" %in% files){
          rv$data <- read.CPDBv2(folder = input_folder())
        } else {
          shinyalert(text = "The selected folder does not contain CPDB output files!
                     Please select the correct folder.", 
                     type = "error",
                     showCancelButton = FALSE)
        }
        
      }
      else if(input$select_input_tool == 'scsignalR'){
        files <- list.files(input_folder())
        if(all(grep("LR_interactions", files))){
          rv$data <- read.SCsignalR(folder = input_folder())
        } else{
          shinyalert(text = "The selected folder does not contain 
          SingleCellSignalR output files!
                     Please select the correct folder.", 
                     type = "error",
                     showCancelButton = FALSE)
        }
        
      }
      
    })
    
    
    ### For supported tools requiring files
    observeEvent(input$input_file_button, {
      file <- input$input_file
      req(file)
      ext <- tools::file_ext(file$datapath)
      
      validate(need(ext %in% c("csv", "tsv", "xlsx"), "Please choose a file
                    with the required extension (.csv/.tsv/.xlsx)."))
      switch (ext,
              csv = {tryCatch({
                tab <- read.csv(file$datapath, header = TRUE)
                if("X" %in% colnames(tab)){
                  tab <- tab[, !colnames(tab) == "X"]
                }
              },
              error = function(e) {
                # return a safeError if a parsing error occurs
                stop(safeError("Error reading input file"))
              }
              )},
              tsv = {tryCatch({
                tab <- read.table(file$datapath, sep = "\t", 
                                  header = TRUE)
              },
              error = function(e) {
                # return a safeError if a parsing error occurs
                stop(safeError("Error reading input file"))
              }
              )},
              xlsx = {tryCatch({
                tab <- read_excel(file$datapath, col_names = TRUE)
              },
              error = function(e) {
                # return a safeError if a parsing error occurs
                stop(safeError("Error reading input file"))
              }
              )}
      )
      
      # Checks on required columns
      if(input$select_input_tool == 'cellchat'){
        req.columns <- c("source", "target", "ligand", "receptor", "prob", "pval", 
                         "interaction_name", "interaction_name_2", "pathway_name",
                         "annotation", "evidence")
        if(!all(req.columns %in% colnames(tab))){
          missing.col <- req.columns[!(req.columns %in% colnames(tab))]
          shinyalert(text = paste("Looks like these required columns are missing:", 
                                  paste(missing.col, collapse = " "), sep = " "), 
                     type = "error",
                     showCancelButton = FALSE)
        } else {
          rv$data <- read.cellchat(tab)
        }
      }
      
      
    })
    
  
    
      

    
    observeEvent(rv$data, {
      shinyalert(text = "Your data was successfully loaded and preprocessed! 
             Check it out at table view!", type = "success",
                 showCancelButton = FALSE)
      
    })
    
    
    return(rv)
  })
}
    

