#' upload UI Function
#'
#' @description A shiny Module.
#'
#' @param id,input,output,session Internal parameters for {shiny}.
#'
#' @noRd 
#'
#' @importFrom shiny NS tagList fluidRow column selectInput conditionalPanel 
#' textOutput tabPanel
#' @importFrom shinyFiles shinyDirButton shinyDirChoose getVolumes parseDirPath
#' @importFrom shinydashboard tabBox 
#' @importFrom fs path_home


mod_upload_ui <- function(id){
  ns <- NS(id)
  text.cpdb <- "Please select the output folder generated by CPDB (v2). When the
  statistical analysis was run, this folder contains 4 .txt files 
  (<em>deconvoluted</em>, <em>means</em>, <em>pvalues</em> and 
  <em>significant_means</em>). In this case, InterCellar will use results stored
  in <em>significant_means</em> for further analyses. If no statistical analysis
  was run, InterCellar will rely on <em>means</em>."
  text.scsignalR <- "Please select the output folder generated by 
  SingleCellSignalR. This is by default named <em>cell-signaling</em> and 
  contains a collection of .txt files, one for each clusters pair considered."
  
  tagList(
    fluidRow(
      column(width = 6,
             h2("Upload cell-cell interactions")),
      
      
    ),
    
      tabBox(
        width = NULL,
        
        
        tabPanel(h4("From supported tools"),
                 fluidRow(
                   column(4,
                          selectInput(ns("select_input_tool"),
                                      label = h4("Select tool:"),
                                      choices = list("CellPhoneDB v2" = "cpdbv2",
                                                     "SingleCellSignalR" = "scsignalR"),
                                      multiple = FALSE)
                   ),
                   column(8,
                          conditionalPanel(
                            condition = "input.select_input_tool == 'cpdbv2'",
                            ns = ns,
                            p(div(HTML(text.cpdb)))
                            
                            
                          ),
                          conditionalPanel(
                            condition = "input.select_input_tool == 'scsignalR'",
                            ns = ns,
                            p(div(HTML(text.scsignalR)))
                            
                            
                          ),
                          shinyFiles::shinyDirButton(ns("directory"), 
                                                     "Select folder", 
                                                     "Please select a folder")
                   ))),
        tabPanel(h4("From custom analysis"),
                 mod_upload_custom_ui("upload_custom_ui_1")
        )
      )#tabbox
      
             
             
      
  )
  
  
}
    
#' upload Server Function
#'
#' @importFrom shinyalert shinyalert
#' @noRd 
mod_upload_server <- function(id) {
  moduleServer(id, function(input, output, session) {
    
    rv <- reactiveValues(data = NULL)
    
    volumes <- c(Home = fs::path_home(),  getVolumes()())
    shinyDirChoose(input, "directory", roots = volumes, session = session, 
                   restrictions = system.file(package = "base"))
    
    input_folder <- reactive({
      req(input$directory)
      parseDirPath(volumes, input$directory)
    })
    
    # shinyDirChoose(input, "directory_scsignalR", roots = volumes, session = session, 
    #                restrictions = system.file(package = "base"),
    #                allowDirCreate = FALSE)
    # 
    # input_folder_scsignalR <- reactive({
    #   req(input$directory_scsignalR)
    #   parseDirPath(volumes, input$directory_scsignalR)
    # })
    
    # observeEvent(input$select_input_tool, {
    #   if(input$select_input_tool == 'cpdbv2'){
    #     shinyDirChoose(input, "directory_cpdbv2", roots = volumes, session = session, 
    #                    restrictions = system.file(package = "base"),
    #                    allowDirCreate = FALSE)
    #     req(input$directory_cpdbv2)
    #     rv$input_folder <- parseDirPath(volumes, input$directory_cpdbv2)
    # 
    #   } else if(input$select_input_tool == 'scsignalR'){
    #     shinyDirChoose(input, "directory_scsignalR", roots = volumes, session = session, 
    #                    restrictions = system.file(package = "base"),
    #                    allowDirCreate = FALSE)
    #     req(input$directory_scsignalR)
    #     rv$input_folder <- parseDirPath(volumes, input$directory_scsignalR)
    #   
    #   }
    # })
    
    
    
    
    ### Read input and construct datatable
    observeEvent(input$directory, {
      req(input_folder())
      if(input$select_input_tool == 'cpdbv2'){
        files <- list.files(input_folder())
        if("means.txt" %in% files){
          rv$data <- read.CPDBv2(folder = input_folder())
        } else {
          shinyalert(text = "The selected folder does not contain CPDB output files!
                     Please select the correct folder.", 
                     type = "error",
                     showCancelButton = FALSE)
        }
        
      }
      else if(input$select_input_tool == 'scsignalR'){
        files <- list.files(input_folder())
        if(all(grep("LR_interactions", files))){
          rv$data <- read.SCsignalR(folder = input_folder())
        } else{
          shinyalert(text = "The selected folder does not contain 
          SingleCellSignalR output files!
                     Please select the correct folder.", 
                     type = "error",
                     showCancelButton = FALSE)
        }
        
      }
      
    })
    
      

    
    observeEvent(rv$data, {
      shinyalert(text = "Your data was successfully loaded and preprocessed! 
             Check it out at table view!", type = "success",
                 showCancelButton = FALSE)
      
    })
    
    
    return(rv)
  })
}
    

